eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8084
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: product-catalog-service
        predicates: Path= /product/**
        uri: http://localhost:8081/
      
       
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE